dist: trusty

language: android

jdk:
    - openjdk8

android:
    components:
        - tools
        - android-27
        - platform-tools
        - build-tools-27.0.3
        - extra-google-m2repository
        - extra-android-m2repository
        - extra-android-support

script: ./build.sh

before_install:
    - yes | sdkmanager "platforms;android-27" 

cache:
    directories:
        - $HOME/.gradle/caches/
        - $HOME/.gradle/wrapper/

before_cache:
    - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

